# Generated by Django 4.1.6 on 2023-02-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0002_entity_field_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radhatamapp.entity'),
        ),
    ]
