# Generated by Django 4.1.6 on 2023-02-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0003_entity_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='actual_name',
            field=models.CharField(default='STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='field',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='radhatamapp.entity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(default='STRING', max_length=20),
        ),
    ]
