# Generated by Django 4.1.6 on 2023-02-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0006_alter_entity_name_alter_field_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='actual_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
