# Generated by Django 4.1.6 on 2023-02-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0008_alter_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='child',
        ),
        migrations.AddField(
            model_name='field',
            name='child_entity_field_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='child_entity_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
