# Generated by Django 4.1.6 on 2023-02-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0009_remove_entity_child_field_child_entity_field_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='child_entity_field_name',
        ),
        migrations.RemoveField(
            model_name='field',
            name='child_entity_name',
        ),
        migrations.AddField(
            model_name='field',
            name='child_entity_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='child_field_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
