# Generated by Django 4.1.6 on 2023-02-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0010_remove_field_child_entity_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='child_entity_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='child_field_id',
            field=models.IntegerField(null=True),
        ),
    ]
