# Generated by Django 4.1.6 on 2023-02-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0011_alter_field_child_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
