# Generated by Django 4.1.6 on 2023-02-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0012_alter_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_derived_column',
            field=models.BooleanField(default=False),
        ),
    ]
