# Generated by Django 4.1.6 on 2023-02-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0013_field_is_derived_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='derived_level',
            field=models.IntegerField(default=0),
        ),
    ]
