# Generated by Django 4.1.6 on 2023-02-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0015_function_argument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('NUMERIC', 'Numeric'), ('DATE', 'Date'), ('BINARY', 'Binary'), ('COLUMN', 'Column')], default='TEXT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DerivedFieldArguments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument_name', models.CharField(max_length=30, null=True)),
                ('argument_value', models.CharField(max_length=30, null=True)),
                ('argument_type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('NUMERIC', 'Numeric'), ('DATE', 'Date'), ('BINARY', 'Binary'), ('COLUMN', 'Column')], default='TEXT', max_length=20),
        ),
        migrations.DeleteModel(
            name='Argument',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.AddField(
            model_name='derivedfieldarguments',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='radhatamapp.field'),
        ),
        migrations.AddField(
            model_name='argumentmeta',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='radhatamapp.functionmeta'),
        ),
        migrations.AddField(
            model_name='field',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radhatamapp.functionmeta'),
        ),
    ]
