# Generated by Django 4.1.6 on 2023-02-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0017_field_derived_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionmeta',
            name='return_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('NUMERIC', 'Numeric'), ('DATE', 'Date'), ('BINARY', 'Binary'), ('COLUMN', 'Column')], default='TEXT', max_length=20),
        ),
    ]
