# Generated by Django 4.1.6 on 2023-02-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0020_rename_derivedfieldarguments_derivedfieldargument'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionmeta',
            name='return_sql',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
