# Generated by Django 4.1.6 on 2023-02-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0021_functionmeta_return_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionmeta',
            name='return_sql',
            field=models.CharField(max_length=1024),
        ),
    ]
