# Generated by Django 4.1.6 on 2023-02-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0022_alter_functionmeta_return_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionmeta',
            name='type',
            field=models.CharField(choices=[('CALCULATION', 'Calculation'), ('VISUALIZE', 'Visualize'), ('DATASCIENCE', 'DATASCIENCE')], default='CALCULATION', max_length=20),
        ),
    ]
