# Generated by Django 4.1.6 on 2023-02-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0023_functionmeta_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentmeta',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('NUMERIC', 'Numeric'), ('DATE', 'Date'), ('BINARY', 'Binary'), ('PNG_IMAGE', 'PNG Image'), ('COLUMN', 'Column'), ('DERIVED', 'Derived')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('NUMERIC', 'Numeric'), ('DATE', 'Date'), ('BINARY', 'Binary'), ('PNG_IMAGE', 'PNG Image'), ('COLUMN', 'Column'), ('DERIVED', 'Derived')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='functionmeta',
            name='return_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('NUMERIC', 'Numeric'), ('DATE', 'Date'), ('BINARY', 'Binary'), ('PNG_IMAGE', 'PNG Image'), ('COLUMN', 'Column'), ('DERIVED', 'Derived')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='functionmeta',
            name='type',
            field=models.CharField(choices=[('CALCULATION', 'Calculation'), ('VISUALIZE', 'Visualize'), ('DATASCIENCE', 'DataScience')], default='CALCULATION', max_length=20),
        ),
        migrations.CreateModel(
            name='FieldFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_condition', models.CharField(max_length=20)),
                ('filter_value', models.CharField(max_length=20)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='radhatamapp.field')),
            ],
        ),
    ]
