# Generated by Django 4.1.6 on 2023-02-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0024_alter_argumentmeta_type_alter_field_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldfilter',
            old_name='filter_condition',
            new_name='filter_op',
        ),
    ]
