# Generated by Django 4.1.6 on 2023-02-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0025_rename_filter_condition_fieldfilter_filter_op'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldfilter',
            name='field',
        ),
        migrations.AddField(
            model_name='fieldfilter',
            name='field_col',
            field=models.CharField(default='company', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldfilter',
            name='filter_op',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fieldfilter',
            name='filter_value',
            field=models.CharField(max_length=30),
        ),
    ]
