# Generated by Django 4.1.6 on 2023-02-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0034_alter_fieldfilter_filter_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldfilter',
            name='filter_op',
            field=models.CharField(choices=[('EQ', 'Exact'), ('NEQ', 'Not')], default='EQ', max_length=30),
        ),
    ]
