# Generated by Django 4.1.7 on 2023-03-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0036_alter_fieldfilter_filter_op_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='actual_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('NUMERIC', 'Numeric'), ('DATE', 'Date'), ('BINARY', 'Binary'), ('PNG_IMAGE', 'PNG Image'), ('COLUMN', 'Column'), ('DERIVED', 'Derived')], default='TEXT', max_length=64),
        ),
    ]
