# Generated by Django 4.2 on 2023-05-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0038_functionmeta_function_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_calculated_field',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
