# Generated by Django 4.1.7 on 2023-05-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0042_field_datatype_alter_argumentmeta_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivedfieldargument',
            name='argument_value',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='fieldfilter',
            name='filter_op',
            field=models.CharField(choices=[('eq', 'Exact'), ('not', 'Not'), ('lt', 'Less Than')], default='EXACT', max_length=30),
        ),
        migrations.AlterField(
            model_name='functionmeta',
            name='type',
            field=models.CharField(choices=[('CALCULATION', 'Calculation'), ('VISUALIZE', 'Visualize'), ('DATASCIENCE', 'DataScience'), ('GENERATED', 'Generated')], default='CALCULATION', max_length=20),
        ),
    ]
