# Generated by Django 4.1.7 on 2023-05-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0043_alter_derivedfieldargument_argument_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionmeta',
            name='return_sql',
            field=models.TextField(),
        ),
    ]
