# Generated by Django 4.1.7 on 2023-06-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0046_alter_field_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivedfieldargument',
            name='argument_name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
