# Generated by Django 4.1.7 on 2023-06-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0047_alter_derivedfieldargument_argument_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivedfieldargument',
            name='argument_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
