# Generated by Django 4.1.7 on 2023-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radhatamapp', '0049_alter_derivedfieldargument_argument_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataScienceTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('last_run', models.DateTimeField()),
                ('stored_model', models.BinaryField()),
            ],
        ),
    ]
