apiVersion: apps/v1
kind: Deployment

metadata:
  name: superset
  labels:
    app: superset-deployment

spec:
  selector:
    matchLabels:
      app: superset-deployment
  template:
    metadata:
      labels:
        app: superset-deployment
    spec:
      containers:
      - name: superset
        image: apache/superset:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: superset-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: superset-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080